
.include <bsd.opts.mk>

NOMAN=	1

LIB=		stuff

SRCS=		convenience.c

#SRCS+=		am_demod.c dc_block.c deemph.c
#SRCS+=		fm_demod.c
SRCS+=		generic_fir.c fifth_order.c
#SRCS+=		low_pass.c polar_discriminant.c
SRCS+=		remove_dc.c resample.c rms.c mad.c
SRCS+=		rotate_90.c
#SRCS+=		ssb_demod.c

CFLAGS=		-I/usr/local/include

.include <bsd.lib.mk>
